# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackWay System' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for DeliveryApp
  
  pod 'DropDown'
  pod 'Toast-Swift'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore' 
  pod 'FirebaseRemoteConfig' 
  pod 'GoogleMaps'
  pod 'NVActivityIndicatorView'
  pod 'IQKeyboardManager'
  pod 'Polyline'
  pod 'GeoFire/Utils'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
  
end
